// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package session_test

import (
	"strings"
	"sync"
	"sync/atomic"
	"testing"
	"time"

	"google.golang.org/adk/v2/platform"
	"google.golang.org/adk/v2/session"
	"google.golang.org/adk/v2/session/sessiontestsuite"
)

func Test_inMemoryService_CreateUsesProviders(t *testing.T) {
	fixedTime := time.Date(2024, time.January, 2, 3, 4, 5, 0, time.UTC)
	ctx := platform.WithTimeProvider(t.Context(), func() time.Time { return fixedTime })
	ctx = platform.WithUUIDProvider(ctx, func() string { return "fixed-session-id" })

	s := session.InMemoryService()
	resp, err := s.Create(ctx, &session.CreateRequest{AppName: "app", UserID: "user"})
	if err != nil {
		t.Fatalf("Create() error = %v", err)
	}
	if got := resp.Session.ID(); got != "fixed-session-id" {
		t.Errorf("autogenerated session ID = %q, want provider value %q", got, "fixed-session-id")
	}
	if got := resp.Session.LastUpdateTime(); !got.Equal(fixedTime) {
		t.Errorf("LastUpdateTime() = %v, want provider value %v", got, fixedTime)
	}
}

func Test_inMemoryService(t *testing.T) {
	opts := sessiontestsuite.SuiteOptions{SupportsUserProvidedSessionID: true} // InMemory supports custom IDs
	sessiontestsuite.RunServiceTests(t, opts, func(t *testing.T) session.Service {
		return session.InMemoryService()
	})
}

func Test_inMemoryService_CreateConcurrentAccess(t *testing.T) {
	s := session.InMemoryService()
	const goroutines = 16
	const attempts = 32

	start := make(chan struct{})
	var wg sync.WaitGroup
	wg.Add(goroutines)

	req := &session.CreateRequest{
		AppName:   "race-app",
		UserID:    "race-user",
		SessionID: "race-session",
	}

	var successCount atomic.Int32
	var errorCount atomic.Int32

	for range goroutines {
		go func() {
			defer wg.Done()
			<-start
			for range attempts {
				_, err := s.Create(t.Context(), req)
				if err == nil {
					successCount.Add(1)
				} else if strings.Contains(err.Error(), "already exists") {
					errorCount.Add(1)
				}
			}
		}()
	}

	close(start)
	wg.Wait()

	if successCount.Load() != 1 {
		t.Errorf("expected 1 successful creation, but got %d", successCount.Load())
	}

	expectedErrors := int32(goroutines*attempts - 1)
	if errorCount.Load() != expectedErrors {
		t.Errorf("expected %d 'already exists' errors, but got %d", expectedErrors, errorCount.Load())
	}
}

// TestInMemorySession_AppendEvent_WorkflowFieldsRoundTrip guards that
// AppendEvent persists the workflow event fields (NodeInfo,
// RequestedInput, Routes, IsolationScope) — workflow resume rehydrates
// node state from them, and a manual event copy that drops them breaks
// HITL resume. IsolationScope additionally drives history filtering.
func TestInMemorySession_AppendEvent_WorkflowFieldsRoundTrip(t *testing.T) {
	ctx := t.Context()
	service := session.InMemoryService()

	createResp, err := service.Create(ctx, &session.CreateRequest{AppName: "app", UserID: "user"})
	if err != nil {
		t.Fatalf("Create: %v", err)
	}
	sess := createResp.Session

	const wantScope = "adk-task-isolation-scope"
	event := &session.Event{
		ID:             "wf_event",
		Author:         "agent",
		IsolationScope: wantScope,
		NodeInfo:       &session.NodeInfo{Path: "ask_name"},
		RequestedInput: &session.RequestInput{InterruptID: "ask_name", Message: "What's your name?"},
		Routes:         []string{"route_a"},
	}
	if err := service.AppendEvent(ctx, sess, event); err != nil {
		t.Fatalf("AppendEvent: %v", err)
	}

	got, err := service.Get(ctx, &session.GetRequest{AppName: "app", UserID: "user", SessionID: sess.ID()})
	if err != nil {
		t.Fatalf("Get: %v", err)
	}
	evs := got.Session.Events()
	if evs.Len() != 1 {
		t.Fatalf("got %d events, want 1", evs.Len())
	}
	ev := evs.At(0)
	if ev.NodeInfo == nil || ev.NodeInfo.Path != "ask_name" {
		t.Errorf("NodeInfo not persisted: %#v", ev.NodeInfo)
	}
	if ev.RequestedInput == nil || ev.RequestedInput.InterruptID != "ask_name" {
		t.Errorf("RequestedInput not persisted: %#v", ev.RequestedInput)
	}
	if len(ev.Routes) != 1 || ev.Routes[0] != "route_a" {
		t.Errorf("Routes not persisted: %#v", ev.Routes)
	}
	if ev.IsolationScope != wantScope {
		t.Errorf("IsolationScope = %q, want %q", ev.IsolationScope, wantScope)
	}
}

func TestInMemorySession_AppendEvent_Deadlock(t *testing.T) {
	ctx := t.Context()
	service := session.InMemoryService()

	// Create a session
	createReq := &session.CreateRequest{
		AppName: "testapp",
		UserID:  "testuser",
	}
	createResp, err := service.Create(ctx, createReq)
	if err != nil {
		t.Fatalf("Failed to create session: %v", err)
	}
	sess := createResp.Session

	// Event with StateDelta to trigger updateSessionState
	event := &session.Event{
		ID:        "event1",
		Timestamp: time.Now(),
		Actions: session.EventActions{
			StateDelta: map[string]any{
				"test_key": "test_value",
			},
		},
	}

	// This call should hang if the deadlock is present
	err = service.AppendEvent(ctx, sess, event)
	if err != nil {
		t.Fatalf("AppendEvent failed: %v", err)
	}

	// If it doesn't hang, the test passes (meaning no deadlock)
	t.Log("AppendEvent did not deadlock")
}

func TestInMemoryService_AppendEvent_PreservesInputEventTempState(t *testing.T) {
	ctx := t.Context()
	service := session.InMemoryService()

	createResp, err := service.Create(ctx, &session.CreateRequest{
		AppName: "testapp",
		UserID:  "testuser",
	})
	if err != nil {
		t.Fatalf("Failed to create session: %v", err)
	}

	event := &session.Event{
		ID:        "event1",
		Timestamp: time.Now(),
		Actions: session.EventActions{
			StateDelta: map[string]any{
				"temp:k1": "v1",
				"sk":      "v2",
			},
		},
	}

	if err := service.AppendEvent(ctx, createResp.Session, event); err != nil {
		t.Fatalf("AppendEvent failed: %v", err)
	}

	// Verify that the input event pointer's StateDelta map was not mutated in place.
	if _, exists := event.Actions.StateDelta["temp:k1"]; !exists {
		t.Errorf("expected temp:k1 to be preserved on input event after AppendEvent, but it was removed: %v", event.Actions.StateDelta)
	}
	if event.Actions.StateDelta["sk"] != "v2" {
		t.Errorf("expected non-temp key sk to remain in input event, got: %v", event.Actions.StateDelta)
	}

	// Verify that the stored event in the session has temp keys stripped.
	var storedEvent *session.Event
	for ev := range createResp.Session.Events().All() {
		storedEvent = ev
	}
	if storedEvent == nil {
		t.Fatalf("expected stored event in session, got nil")
	}
	if _, exists := storedEvent.Actions.StateDelta["temp:k1"]; exists {
		t.Errorf("expected temp:k1 to be stripped from stored event, but it still exists: %v", storedEvent.Actions.StateDelta)
	}
	if storedEvent.Actions.StateDelta["sk"] != "v2" {
		t.Errorf("expected non-temp key sk on stored event, got: %v", storedEvent.Actions.StateDelta)
	}
}

func TestInMemoryService_DefensiveMapInit(t *testing.T) {
	ctx := t.Context()
	// Create service directly to test zero-initialized struct fields
	service := session.InMemoryService()

	resp, err := service.Create(ctx, &session.CreateRequest{
		AppName: "app1",
		UserID:  "user1",
		State: map[string]any{
			"app:k1":  "v1",
			"user:k2": "v2",
		},
	})
	if err != nil {
		t.Fatalf("Create failed: %v", err)
	}

	val, err := resp.Session.State().Get("app:k1")
	if err != nil || val != "v1" {
		t.Errorf("expected app:k1 to be v1, got %v, err=%v", val, err)
	}
}

